language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2.4
  - 2.3.0
  - ruby-head
gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
matrix: 
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
  exclude:
    - rvm: 1.9
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5_0.gemfile
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
