language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - Gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
